name: myenv
channels:
  - defaults
dependencies:
  - ca-certificates=2024.7.2
  - glpk=4.65
  - gmp=6.2.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.14
  - pip=24.2  # Pip is included here, but pip packages will be installed via requirements.txt
  - python=3.8.19
  - readline=8.2
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13