name: myenv
channels:
  - defaults
dependencies:
  - ca-certificates=2024.7.2
  - glpk=4.65
  - gmp=6.2.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.14
  - pip=24.2
  - python=3.8.19
  - readline=8.2
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip   # Ensure pip is installed
  - pip:
    - blinker==1.8.2
    - certifi==2024.8.30
    - charset-normalizer==3.3.2
    - click==8.1.7
    - dash==2.17.1
    - dash-bootstrap-components==1.6.0
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - dash_cytoscape==1.0.2
    - Flask==3.0.3
    - idna==3.8
    - importlib_metadata==8.4.0
    - itsdangerous==2.2.0
    - Jinja2==3.1.4
    - MarkupSafe==2.1.5
    - nest-asyncio==1.6.0
    - networkx==3.1
    - numpy==1.24.4
    - packaging==24.1
    - pandas==2.0.3
    - plotly==5.24.0
    - ply==3.11
    - Pyomo==6.8.0
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - requests==2.32.3
    - retrying==1.3.4
    - six==1.16.0
    - tenacity==9.0.0
    - typing_extensions==4.12.2
    - tzdata==2024.1
    - urllib3==2.2.2
    - Werkzeug==3.0.4
    - zipp==3.20.1
    - gunicorn
